# Generated by Django 5.1.1 on 2024-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseCode', models.CharField(max_length=5)),
                ('courseName', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=1)),
                ('year', models.CharField(max_length=4)),
                ('seat', models.CharField(max_length=4)),
            ],
        ),
    ]
