# Generated by Django 5.1.1 on 2024-09-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseCode',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seat_is_full',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='seat',
            field=models.IntegerField(),
        ),
    ]
